"""Change name

Revision ID: c18f4a3e304d
Revises: 6153d206a05b
Create Date: 2025-03-12 17:20:51.163717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18f4a3e304d'
down_revision: Union[str, None] = '6153d206a05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliaition_products')
    op.drop_table('reconciliation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.VARCHAR(), nullable=False),
    sa.Column('place_id', sa.INTEGER(), nullable=False),
    sa.Column('place_name', sa.VARCHAR(), nullable=False),
    sa.Column('uploaded', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliaition_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reconciliation_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(), nullable=False),
    sa.Column('product_rid', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
