PROC_NAME_FIND_GOODS_BY_GROUP = "Goods"
PROC_NAME_ALL_GROUPS = "GGroups"
PROC_NAME_PROPERTY = 'GoodsItem'
PROC_NAME_FIND_BY_BARCODE = 'SrchGoods'
PROC_NAME_FIND_REMAINING_PRODUCTS_BY_GROUP_ID = 'GRemns'
PROC_NAME_CREATE_RECONCILIATION = "InsGDoc8"

LOGIN_PROC_NAME = "InsGDoc8"
